### ISSUE TITLE
Gateway panel is not showing data

### ISSUE THREAD

**Issue by tismofied** [bsmithio/OPNsense-Dashboard#39]
As the title. The Gateway panel shows unavailable, and data is being streamed. 
I noticed in another issue that not adding `sudo` to `telegraf_pfifgw.php` the gateway doesn't work. I did exactly whats in the guide. but it's still blank. 

[Image](https://imgur.com/a/u2LLFID)

**Comment by tismofied** [comment]
any ideas @bsmithio ?

**Comment by bsmithio** [comment]
> any ideas @bsmithio ?

Try this command on an OPNsense shell

`sudo su -m telegraf -c 'telegraf --test --config /usr/local/etc/telegraf.conf --config-directory /usr/local/etc/telegraf.d'`

Do you get any gateway stats there?

**Comment by tismofied** [comment]
I get this output:
`> gateways,gateway_name=WAN_DHCP,host=MY HOST NAME HERE,interface=wan delay=0,gwdescr="Interface WAN_DHCP Gateway",loss=0,monitor="Unmonitored",source="public ip here",status="Unavailable",stddev=0`

**Comment by jsa91** [comment]
Having the same issue.

`gateway_name=WAN_DHCP monitor="Unmonitored"`
`status="Unavailable"`

**Comment by bsmithio** [comment]
I'm trying to replicate this but the only progress I've found is going to the gateway under System -> Gateways -> Single -> Edit gateway -> and seeing if "Disable gateway monitoring" is checked. If it is, uncheck it and apply. This should fix that issue.

**Comment by phaelon74** [comment]
> I'm trying to replicate this but the only progress I've found is going to the gateway under System -> Gateways -> Single -> Edit gateway -> and seeing if "Disable gateway monitoring" is checked. If it is, uncheck it and apply. This should fix that issue.

The challenge I see, is I uncheck that but when I run the command at CLI, it still shows the interface as Unmonitored and nothing shows up in the dashboard:
`> gateways,gateway_name=WAN_GW_2,host=FW01,interface=wan delay=0.3,gwdescr="Interface WAN Gateway",loss=0,monitor="Unmonitored",source="XX.YY.WW.ZZ",status="1",stddev=0 NUMBER
`

But I can now see stats on the interface, which I could not before I unchecked the Do Not Monitor:

**Comment by phaelon74** [comment]
![image](https://github.com/bsmithio/OPNsense-Dashboard/assets/33295008/85186c19-36d2-485e-98e5-57b51c11790d)
